import "./globals.css";
import { Inter } from "next/font/google";
import { Header } from "@/src/components/Header";
import { Sidebar } from "@/src/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className='h-full' lang='en'>
      <body className='h-full bg-gray-100'>
        <Header />
        <main className='flex h-full overflow-y-auto'>
          <Sidebar />
          <div className='flex-1 mt-36 p-10'>{children}</div>
        </main>
      </body>
    </html>
  );
}
